### PR TITLE
Finalized Apple Landing Page Replica Project

### PR DESCRIPTION
**Pull request by java-cromium**
Completed the final details from the Apple Landing Page replica development project. The latest changes consisted of adding the footer items along with fixing some spacing and aesthetics aspects from the navbar and hero section.

### CODE REVIEW

**Review by euqueme — CHANGES_REQUESTED** [review]
> Pull Request validated by Maria Eugenia Quemé P. (TSE)

### Hello @java-cromium :wave: 

- [ ] I can't start the review because your project is missing a Descriptive Readme format to make it valid.

### Please modify your Readme file using this [template](https://github.com/microverseinc/readme-template) and submit back for a Code Review when you are done.

STATUS OF THE PROJECT: INVALID :stop_sign:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Currently writing your review! Please check on it in about an hour for some feedback, thank you :100:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job @java-cromium!
This is really nice :smile:. There are a few things you need to address before we can approve your project. Please consider my comments below.

#### HTML Validation
Please condsider parsing your HTML markup through this validator and correct all resulting errors. It is mandatory that your markup is free from semantic or syntax errors.
screenshot

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

#### Missing search box
Please compare your navigation bar with that of the original site and you may find that one of the elements(the search box) is missing.

### Summary
You have done a really nice job, I love your gradient. Please look into the few changes I am proposing, make required adjustments and submit for a re-review! :handshake: See you at the top :rocket: 
##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by rOluochKe — APPROVED** [review]
Hello @java-cromium 

### Congratulations :clap: your project has passed review. Now merge submit a project completion form from your dashboard. 
### You can move on to the next project. I wish you all the best. 
- Happy coding!

**Pull request merged**
